name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  patterns:
    description: File patterns to run against
    default: ''
runs:
  using: 'node12'
  main: 'lib/main.js'
