name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  github-token:
    description: Github token for posting check run
    required: true
  patterns:
    description: File patterns to run against
    default: ''
  post-annotations:
    description: Post annotations (vs. letting problem matchers scrape them)
    required: false
    default: 'false'
runs:
  using: 'node12'
  main: 'lib/main.js'
