name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - run: npm ci

      - run: npm run build

      - name: eslint
        uses: harveyr/gh-action-eslint@releases/v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          patterns: src/**.ts

      - run: npm test

      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
